site_name: Toolip
site_url: https://example.com/
repo_url: https://github.com/SatelCreative/toolip
nav:
  - Home: index.md
  - Modules:
      - FastAPI: fastapi.md
      - Utils: utils.md
theme: readthedocs
