site_name: Toolip
site_url: https://example.com/
repo_url: https://github.com/SatelCreative/toolip
theme:
  name: material
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - ...
plugins:
  - search
  - awesome-pages
