name: Compare index and readme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: Test files
        run: |
          DIFF=$(diff README.md docs/index.md)
          if [ "$DIFF" != "" ]; then
              echo "$DIFF"
              exit 1
          else
              exit 0
          fi
