name: Build documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install lazydocs pydocstyle
      - name: Build lazydocs
        run: |
          lazydocs --overview-file="index.md" --src-base-url="https://github.com/SatelCreative/toolip/tree/main" --output-path="./docs/api-docs" --validate .
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          # CONFIG_FILE: ../mkdocs.yml
          EXTRA_PACKAGES: build-base
          REQUIREMENTS: docs/requirements.txt
          # GITHUB_DOMAIN: github.myenterprise.com
